version: '3'

services:

  web:
    build: .
    container_name: bert_django
    command: python3 manage.py runserver 0.0.0.0:8000
    working_dir: /src
    volumes:
      - .:/src
    ports:
      - "8090:8000"
    